export const GET_AUTH_DATA_SUCCESS = '@@auth/GET_AUTH_DATA_SUCCESS'
export const GET_AUTH_DATA_FAILURE = '@@auth/GET_AUTH_DATA_FAILURE'
export const LOGOUT = '@@auth/LOGOUT'

export const ADD_CHAT = '@@chats/ADD_CHAT'
export const UPDATE_MESSAGE = '@@chats/UPDATE_MESSAGE'
export const GET_CHATS_SUCCESS = '@@chats/GET_CHATS_SUCCESS'
export const GET_CHATS_FAILURE = '@@chats/GET_CHATS_FAILURE'

export const ADD_MESSAGE = '@@messages/ADD_MESSAGE'
export const GET_CHAT_MESSAGES = '@@messages/GET_CHAT_MESSAGES'
export const SEND_MESSAGE_SUCCESS = '@@messages/SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAILURE = '@@messages/SEND_MESSAGE_FAILURE'
export const GET_MESSAGES_SUCCESS = '@@messages/GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAILURE = '@@messages/GET_MESSAGES_FAILURE'

export const CENTRIFUGE_DISCONNECT = '@@centrifuge/CENTRIFUGE_DISCONNECT'
export const CENTRIFUGE_CONNECT_SUCCESS =
  '@@centrifuge/CENTRIFUGE_CONNECT_SUCCESS'
export const CENTRIFUGE_CONNECT_FAILURE =
  '@@centrifuge/CENTRIFUGE_CONNECT_FAILURE'
export const CHANNEL_SUBSCRIBE_SUCCESS =
  '@@centrifuge/CHANNEL_SUBSCRIBE_SUCCESS'
export const CHANNEL_SUBSCRIBE_FAILURE =
  '@@centrifuge/CHANNEL_SUBSCRIBE_FAILURE'
export const CENTRIFUGE_INITIAL_SUBSCRIBE = '@@centrifuge/INITIAL_SUBSCRIBE'
